-- Hotfix: create_campaign errored with
--   duplicate key value violates unique constraint "campaigns_pkey"
-- when Aaron tried to add "Jaws Explored".
--
-- Cause: campaigns.id is GENERATED BY DEFAULT AS IDENTITY, so explicit
-- id values in INSERTs are allowed and do NOT advance the sequence.
-- Somewhere between the IDENTITY migration (task #72) and today,
-- campaigns 11-17 were inserted with explicit ids (most likely during
-- the ISOD 70s split — 20260626150000_isod_70s_legacy_code_rename or
-- an ad-hoc INSERT), leaving:
--     max(id)                      = 17
--     sequence.last_value          = 10
-- Next nextval hands out 11 → collides with the existing row → 23505.
--
-- Fix: setval the sequence to the current max(id). nextval then returns
-- max(id) + 1 as expected. Idempotent — safe to re-run.
--
-- If this recurs, the culprit is another manual INSERT with an explicit
-- id. Either use DEFAULT for id, or run setval again after the import.

select setval(
  pg_get_serial_sequence('aa_01_campaigns.campaigns', 'id'),
  (select max(id) from aa_01_campaigns.campaigns)
);
